title: Kashyap Prajapati
name: Kashyap Prajapati

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/kashyap-prajapati
 - title: LinkedIn
   url: https://www.linkedin.com/pub/rob-hinds/21/361/3b1

#Any buzzword skills you want to include
skills:
 - Spring Boot
 - Spring MVC
 - Maven
 - Advanced Java
 - Oracle
 - MY SQL
 - Algorithms
 - Data Structure
 - Core Java
 - Java Script
 - JQuery

theme: jekyll-theme-minimal
